### ISSUE TITLE
Deploy failed on travis

### ISSUE THREAD

**Issue by Tataro** [Redocly/create-openapi-repo#39]
Hi,
I got this message in travis log 'Deploy failed: Error: Unspecified error (run without silent option for detail)', any idea?

**Comment by Tataro** [comment]
I guess the cause is from GitHub token, but don't know what's wrong. for now, my workaround is to change travis.yml file.
```yml
language: node_js
node_js:
  - "node"
before_script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: web_deploy/
  on:
    branch: master
```
